### ISSUE TITLE
Route name should allow 0-9

### ISSUE THREAD

**Issue by baer** [TestArmada/drydock#1]
Right now name only accepts `[A-Za-z\-]` but I'm trying to use it with a customer ID which has `0-9`. Happy to PR this if you're interested.

https://github.com/TestArmada/drydock/blob/0b5923816a4951a7db6de1a3f6bf383819449cfe/lib/schemas.js#L25

```
drydock.jsonRoute({
  name: "ABC0001",
  method: "GET",
  path: "/customers/ABC0001",
  handlers: {
    "success": {
      description: "Return customer ABC0001",
      handler: function () {
        return require("./data/customers-ABC0001.json");
      }
    }
  }
});
```

**Comment by divmain** [comment]
PR welcome for this also.  Thanks!
