### ISSUE TITLE
Allow for case insensitive routes

### ISSUE THREAD

**Issue by biglovisa** [TestArmada/drydock#18]
Is there a reason for why Drydock does not support case insensitive routes? Would you be open to add support for case insensitive routes? 

We are using Drydock for one of our testing strategies and are very happy with it. Adding support for case insensitive routes is necessary for us, and we are already using a fork of the project where we can do so. However, we don't want to put ourselves in a situation where it's impossible to drop our fork and use the main version.

**Comment by divmain** [comment]
Hi @applegrain!  I see no issue with adding support for case-insensitive routes.  Additionally, if the Rally team is interested, I'd be happy to add some team-members as collaborators on the project.  I wouldn't want any unresponsiveness on my end to slow you all down, and the project is not central to my work any longer.  Let me know your thoughts!

**Comment by biglovisa** [comment]
Great! I just submitted a PR to add support for case insensitive routes. 

We really appreciate your offer to add some of us as contributors! This quarter we have put active development of that product on hold, so there probably won't be a ton of changes coming up in the next few months. I'm happy with leaving things as they are now and we can come back to it if the situation changes. 

Thanks! (and thank you for a great project 👍)

**Comment by divmain** [comment]
Closed by #19.
