### ISSUE TITLE
Path should allow all unicode characters

### ISSUE THREAD

**Issue by baer** [TestArmada/drydock#2]
A path currently can only contain `regex(/^[A-Za-z\-\/\_\{\}]+$/)` but a URl can contain any valid unicode character including emoji. Practically speaking this prevents the use of User or Product IDs in a resource name which would be common for a RESTful API.

https://github.com/TestArmada/drydock/blob/0b5923816a4951a7db6de1a3f6bf383819449cfe/lib/schemas.js#L27

Happy to PR this if you are interested.

**Comment by divmain** [comment]
Thanks @baer - PR on this very welcome.
