### ISSUE TITLE
Version 0.8.0 doesn't have a lib folder

### ISSUE THREAD

**Issue by biglovisa** [TestArmada/drydock#21]
The latest version unfortunately does not have a `lib` folder. Would you mind building and pushing it up to npm?
 
<img width="476" alt="screen shot 2017-03-20 at 5 58 55 pm" src="https://cloud.githubusercontent.com/assets/10555255/24126991/ecbbb4fc-0d96-11e7-8d6c-aa8153d81397.png">

**Comment by divmain** [comment]
Sorry about that! `v0.8.1` is published with the changes.

**Comment by biglovisa** [comment]
Awesome! Thanks so much :1st_place_medal:
