### ISSUE TITLE
Move from TestArmada org

### ISSUE THREAD

**Issue by divmain** [TestArmada/drydock#7]
@Maciek416 @geekdave - looks like this isn't being used internally.  Would you mind if I move this to a new location, so I can continue to maintain it for my own use?

**Comment by geekdave** [comment]
Hey @divmain - Yeah that's a good idea.  Do you need help doing this or do you have the perms?  If you do, please go ahead.

**Comment by divmain** [comment]
Thanks @geekdave - I got it sorted.  Hope you guys are doing well.
